sudo: required
services:
  - docker

install: docker pull dpollet/texlive:pillar

script: |
  docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar bash -c "\
    wget --quiet --output-document=- 'https://raw.githubusercontent.com/pillar-markup/pillar/master/download.sh' | bash \
    && make spiralbook \
  "

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-MetaModelingInMoose
  skip_cleanup: true
  user: ducasse
  key:
    secure: la9cknDFpRzmyNZ98raRJesEpgj1QOcmNLWXvBmh3OwjqSk9QwqoUHTu+AEeCu8spLd00YMz3YJuy4ozSBdTxdkNJZUYPQPv+PTDumFRa81KkLP7wor2ieIV6/kcRTwLESPj6M/f0qAM0mfu17S0Bq17snc+kBuafWReTxg0Og41bGomfQRxL6F+an+lfNhQX7nNQXUBO+N5rmMHc4K2SRK2hL9qCNFMNOJc8WmcTOaAZAiXEtqrLGnm/f7Vwh/sMMgKQHBgf1OSbYwB3AStVeSyVqFmksYVlLyWJFe39jORgEaR0PENo+2NAkAoNVo7I9hlh+QoUJ6l7jtJ53jHIERZg1YPd81L50Fu6jeoKWIVmXkRshusmPyKBONc1SHSBFBrJaVdA8F8Zc/wCksJ8aXqEHJ7uVz0sXsV+7FGpkCV7OUXMJQMbn8/4QBJ7CvqFM3phge+K7q4o4CfjB/DcIUSSepV3ewboAVCdscbfonpJ1zPqmSKfKjVOqeZ7IZGqPNOWOMEdRYMVAL4DWSE/YGavlLSuzRF/DC/oIkTCouAQsB//G5DS50Z2M7UZmyFC7xyRxYJDTmRiBZz6MAwz1ioQLHbkPuanOQ+m+dC2i2v0giVHelnGBfz0S6Fy6SnjQx7VbejZYX/pcKKwi1eNckGkSZMZh7CqIbs3HGK6aw=
- provider: releases
  file: build/book.spiral.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
